################
## Deployment ##
################

deploy.sonic_mainnet: ## Deploy the contracts
	@yarn hardhat deploy --network sonic_mainnet

deploy.hardhat: ## Deploy the contracts
	@yarn hardhat deploy --network hardhat

.PHONY: deploy.sonic_mainnet
